In [1]:
import pandas as pd

### Carregando base de setores básicos

In [3]:
df_ibge = pd.read_csv(
    'Agregados_por_setores_basico_BR.csv',
    sep=';',
    encoding='latin1',
    low_memory=False
)

In [4]:
df_ibge.columns.tolist()

['CD_SETOR',
 'SITUACAO',
 'CD_SIT',
 'CD_TIPO',
 'AREA_KM2',
 'CD_REGIAO',
 'NM_REGIAO',
 'CD_UF',
 'NM_UF',
 'CD_MUN',
 'NM_MUN',
 'CD_DIST',
 'NM_DIST',
 'CD_SUBDIST',
 'NM_SUBDIST',
 'CD_BAIRRO',
 'NM_BAIRRO',
 'CD_NU',
 'NM_NU',
 'CD_FCU',
 'NM_FCU',
 'CD_AGLOM',
 'NM_AGLOM',
 'CD_RGINT',
 'NM_RGINT',
 'CD_RGI',
 'NM_RGI',
 'CD_CONCURB',
 'NM_CONCURB',
 'v0001',
 'v0002',
 'v0003',
 'v0004',
 'v0005',
 'v0006',
 'v0007',
 'v0008',
 'v0009']

In [7]:
df_setores_slz = (
    df_ibge[df_ibge['NM_MUN'] == 'São Luís']
    [['CD_SETOR', 'AREA_KM2', 'v0001']]
    .copy()
)

df_setores_slz.rename(columns={
    'v0001': 'populacao'
}, inplace=True)

df_setores_slz.head()

              CD_SETOR   AREA_KM2  populacao
52988  211130005000001  0,0777277        236
52989  211130005000002  0,0877081        247
52990  211130005000003  0,1589558        232
52991  211130005000004  0,0744611        213
52992  211130005000005  0,1828716        516

### Carregando bases demograficas

In [14]:
df_demografia = pd.read_csv(
    'Agregados_por_setores_demografia_BR.csv',
    sep=';',
    encoding='latin1',
    low_memory=False
)

In [15]:
df_demografia.head(2)

,CD_setor,V01006,V01007,V01008,V01009,V01010,V01011,V01012,V01013,V01014,...,V01032,V01033,V01034,V01035,V01036,V01037,V01038,V01039,V01040,V01041
0,110001505000002,928,428,500,30,39,24,44,36,25,...,68,62,88,68,58,144,129,124,66,53
1,110001505000003,556,270,286,15,20,20,19,30,20,...,36,47,38,47,44,83,95,48,47,34

### Filtragem do dataset
Seleção de colunas importantes,
Calculo da densidade habitacional e adição dela como coluna

In [10]:
df_setores_slz['AREA_KM2'] = (
    df_setores_slz['AREA_KM2']
    .str.replace(',', '.', regex=False)
)

df_setores_slz['AREA_KM2'] = pd.to_numeric(
    df_setores_slz['AREA_KM2'],
    errors='coerce'
)

In [12]:
df_setores_slz['densidade_hab_km2'] = df_setores_slz['populacao'] / df_setores_slz['AREA_KM2']
df_setores_slz.head()

              CD_SETOR  AREA_KM2  populacao  densidade_hab_km2
52988  211130005000001  0.077728        236        3036.240619
52989  211130005000002  0.087708        247        2816.159511
52990  211130005000003  0.158956        232        1459.525227
52991  211130005000004  0.074461        213        2860.554034
52992  211130005000005  0.182872        516        2821.651913

In [16]:
# Para exportar para csv
df_setores_slz.to_csv(
    'setores_sao_luis.csv',
    sep=';',
    index=False,
    encoding='utf-8-sig'
)