In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("CNES_UBS_Sao-luis.csv", sep=',')

In [4]:
df.columns

Index(['ANO', 'COMPETÊNCIA', 'MACROREGIÃO', 'UF', 'CÓDIGO DO MUNICÍPIO',
       'MUNICÍPIO', 'CNES', 'NOME FANTASIA', 'RAZÃO SOCIAL',
       'CNPJ DO ESTABELECIMENTO', 'CNPJ DA MANTENEDORA', 'ATIVIDADE PRINCIPAL',
       'ATENDIMENTO PRESTADO', 'TIPO DO ESTABELECIMENTO',
       'SUBTIPO DO ESTABELECIMENTO', 'TIPO NOVO DO ESTABELECIMENTO',
       'NATUREZA JURÍDICA CATEGORIA', 'NATUREZA JURÍDICA', 'GESTÃO',
       'CONVÊNIO SUS', 'NÍVEL DE ATENÇÃO', 'TURNO DE ATENDIMENTO',
       'LEITOS EXISTENTES', 'LEITOS SUS', 'STATUS DO ESTABELECIMENTO',
       'LOGRADOURO', 'COMPLEMENTO DO ENDEREÇO', 'TELEFONE', 'CEP', 'BAIRRO',
       'E-MAIL', 'DIRETOR RESPONSÁVEL', 'DATA DO CADASTRO',
       'DATA DE DESATIVAÇÃO', 'location', 'latitude', 'longitude'],
      dtype='str')

In [4]:
df.head(4)

,ANO,COMPETÊNCIA,MACROREGIÃO,UF,CÓDIGO DO MUNICÍPIO,MUNICÍPIO,CNES,NOME FANTASIA,RAZÃO SOCIAL,CNPJ DO ESTABELECIMENTO,...,LOGRADOURO,COMPLEMENTO DO ENDEREÇO,TELEFONE,CEP,BAIRRO,E-MAIL,DIRETOR RESPONSÁVEL,DATA DO CADASTRO,DATA DE DESATIVAÇÃO,location
0,2026,2026/04,NORDESTE,MA,211130,SAO LUIS,2456834,CENTRO DE SAUDE QUEBRA POTE,SECRETARIA MUNICIPAL DE SAUDE,NaN,...,PRACA DO CEMITERIO - S/N,NaN,NaN,65010-000,QUEBRA POTE,leticiamonroe2@gmail.com,LETICIA DE KASSIA COSTA FERES,02/06/2004,-,"-2.6923404,-44.2155818"
1,2026,2026/04,NORDESTE,MA,211130,SAO LUIS,2455838,CENTRO DE SAUDE DO JOAO PAULO,SECRETARIA MUNICIPAL DE SAUDE,NaN,...,RUA GOSTINHO TORRES - S/N,NaN,NaN,65040-150,JOAO PAULO,centrodesaudejoaopaulogestor@gmail.com,VITOR DOUGLAS PEREIRA DE CASTRO,15/04/2004,-,"-2.5445474322498587,-44.273101187415165"
2,2026,2026/04,NORDESTE,MA,211130,SAO LUIS,2645807,CENTRO DE SAUDE SANTA EFIGENIA,SECRETARIA MUNICIPAL DE SAUDE,NaN,...,RUA TANCREDO NEVES - S/N,NaN,NaN,65010-000,SANTA EFIGENIA,santaefigeniausf@gmail.com,ANTONIA MARIA SANTOS DO LAGO,25/11/2002,-,"-2.576758213711975,-44.19195808377194"
3,2026,2026/04,NORDESTE,MA,211130,SAO LUIS,2309440,CENTRO DE SAUDE ITAPERA,SECRETARIA MUNICIPAL DE SAUDE,NaN,...,RUA PRINCIPAL - 21,NaN,NaN,65010-000,ITAPERA,fabiannaadm@hotmail.com,FABIANNA ALBUQUERQUE DA SILVA,02/06/2004,-,"-2.678204820715199,-44.27637353827428"

In [5]:
# Se o campo location estiver no formato:
# -2.6923404,-44.30218
df[['latitude', 'longitude']] = df['location'].str.split(',', expand=True)
# Converter para números
df['latitude'] = df['latitude'].astype(float)
df['longitude'] = df['longitude'].astype(float)

df.head()

,ANO,COMPETÊNCIA,MACROREGIÃO,UF,CÓDIGO DO MUNICÍPIO,MUNICÍPIO,CNES,NOME FANTASIA,RAZÃO SOCIAL,CNPJ DO ESTABELECIMENTO,...,TELEFONE,CEP,BAIRRO,E-MAIL,DIRETOR RESPONSÁVEL,DATA DO CADASTRO,DATA DE DESATIVAÇÃO,location,latitude,longitude
0,2026,2026/04,NORDESTE,MA,211130,SAO LUIS,2456834,CENTRO DE SAUDE QUEBRA POTE,SECRETARIA MUNICIPAL DE SAUDE,NaN,...,NaN,65010-000,QUEBRA POTE,leticiamonroe2@gmail.com,LETICIA DE KASSIA COSTA FERES,02/06/2004,-,"-2.6923404,-44.2155818",-2.692340,-44.215582
1,2026,2026/04,NORDESTE,MA,211130,SAO LUIS,2455838,CENTRO DE SAUDE DO JOAO PAULO,SECRETARIA MUNICIPAL DE SAUDE,NaN,...,NaN,65040-150,JOAO PAULO,centrodesaudejoaopaulogestor@gmail.com,VITOR DOUGLAS PEREIRA DE CASTRO,15/04/2004,-,"-2.5445474322498587,-44.273101187415165",-2.544547,-44.273101
2,2026,2026/04,NORDESTE,MA,211130,SAO LUIS,2645807,CENTRO DE SAUDE SANTA EFIGENIA,SECRETARIA MUNICIPAL DE SAUDE,NaN,...,NaN,65010-000,SANTA EFIGENIA,santaefigeniausf@gmail.com,ANTONIA MARIA SANTOS DO LAGO,25/11/2002,-,"-2.576758213711975,-44.19195808377194",-2.576758,-44.191958
3,2026,2026/04,NORDESTE,MA,211130,SAO LUIS,2309440,CENTRO DE SAUDE ITAPERA,SECRETARIA MUNICIPAL DE SAUDE,NaN,...,NaN,65010-000,ITAPERA,fabiannaadm@hotmail.com,FABIANNA ALBUQUERQUE DA SILVA,02/06/2004,-,"-2.678204820715199,-44.27637353827428",-2.678205,-44.276374
4,2026,2026/04,NORDESTE,MA,211130,SAO LUIS,2698005,CENTRO DE SAUDE DR JOSE RIBAMAR FRAZAO CORREA,SECRETARIA MUNICIPAL DE SAUDE,NaN,...,(98) 3241-5803,65010-000,NOVA REPUBLICA,ilmaralima0808@gmail.com,FRANCISCA ILMARA LIMA DE SOUZA,03/09/2003,-,"-2.6422066246014846,-44.27605244740161",-2.642207,-44.276052

In [8]:
df.to_csv(
    "v2-CNES_UBS_Sao-luis.csv",
    index=False,
    encoding="utf-8-sig"
)

In [7]:
print(df[['latitude', 'longitude']].head())

print(df[['latitude', 'longitude']].dtypes)

print(df.columns)

   latitude  longitude
0 -2.692340 -44.215582
1 -2.544547 -44.273101
2 -2.576758 -44.191958
3 -2.678205 -44.276374
4 -2.642207 -44.276052
latitude     float64
longitude    float64
dtype: object
Index(['ANO', 'COMPETÊNCIA', 'MACROREGIÃO', 'UF', 'CÓDIGO DO MUNICÍPIO',
       'MUNICÍPIO', 'CNES', 'NOME FANTASIA', 'RAZÃO SOCIAL',
       'CNPJ DO ESTABELECIMENTO', 'CNPJ DA MANTENEDORA', 'ATIVIDADE PRINCIPAL',
       'ATENDIMENTO PRESTADO', 'TIPO DO ESTABELECIMENTO',
       'SUBTIPO DO ESTABELECIMENTO', 'TIPO NOVO DO ESTABELECIMENTO',
       'NATUREZA JURÍDICA CATEGORIA', 'NATUREZA JURÍDICA', 'GESTÃO',
       'CONVÊNIO SUS', 'NÍVEL DE ATENÇÃO', 'TURNO DE ATENDIMENTO',
       'LEITOS EXISTENTES', 'LEITOS SUS', 'STATUS DO ESTABELECIMENTO',
       'LOGRADOURO', 'COMPLEMENTO DO ENDEREÇO', 'TELEFONE', 'CEP', 'BAIRRO',
       'E-MAIL', 'DIRETOR RESPONSÁVEL', 'DATA DO CADASTRO',
       'DATA DE DESATIVAÇÃO', 'location', 'latitude', 'longitude'],
      dtype='str')